//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_InteractUI;
        
        private static SteamVR_Action_Boolean p_default_Teleport;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Boolean p_default_GrabGrip;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_default_Squeeze;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_default_SnapTurnRight;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        private static SteamVR_Action_Vector2 p_platformer_Move;
        
        private static SteamVR_Action_Boolean p_platformer_Jump;
        
        private static SteamVR_Action_Vector2 p_buggy_Steering;
        
        private static SteamVR_Action_Single p_buggy_Throttle;
        
        private static SteamVR_Action_Boolean p_buggy_Brake;
        
        private static SteamVR_Action_Boolean p_buggy_Reset;
        
        private static SteamVR_Action_Pose p_mixedreality_ExternalCamera;
        
        private static SteamVR_Action_Single p_hVR_LeftGrip;
        
        private static SteamVR_Action_Single p_hVR_LeftTrigger;
        
        private static SteamVR_Action_Boolean p_hVR_LeftPrimary;
        
        private static SteamVR_Action_Boolean p_hVR_LeftPrimaryTouch;
        
        private static SteamVR_Action_Boolean p_hVR_LeftSecondary;
        
        private static SteamVR_Action_Boolean p_hVR_LeftSecondaryTouch;
        
        private static SteamVR_Action_Boolean p_hVR_LeftMenu;
        
        private static SteamVR_Action_Boolean p_hVR_LeftPrimaryAxisClick;
        
        private static SteamVR_Action_Boolean p_hVR_LeftSecondaryAxisClick;
        
        private static SteamVR_Action_Boolean p_hVR_LeftPrimaryAxisTouch;
        
        private static SteamVR_Action_Boolean p_hVR_LeftTriggerTouch;
        
        private static SteamVR_Action_Boolean p_hVR_LeftThumbTouch;
        
        private static SteamVR_Action_Boolean p_hVR_LeftTriggerNearTouch;
        
        private static SteamVR_Action_Boolean p_hVR_LeftThumbNearTouch;
        
        private static SteamVR_Action_Vector2 p_hVR_LeftPrimaryAxis;
        
        private static SteamVR_Action_Vector2 p_hVR_LeftSecondaryAxis;
        
        private static SteamVR_Action_Boolean p_hVR_LeftSecondaryAxisTouch;
        
        private static SteamVR_Action_Boolean p_hVR_LeftGripButton;
        
        private static SteamVR_Action_Boolean p_hVR_LeftTriggerButton;
        
        private static SteamVR_Action_Single p_hVR_RightGrip;
        
        private static SteamVR_Action_Single p_hVR_RightTrigger;
        
        private static SteamVR_Action_Boolean p_hVR_RightPrimary;
        
        private static SteamVR_Action_Boolean p_hVR_RightPrimaryTouch;
        
        private static SteamVR_Action_Boolean p_hVR_RightSecondary;
        
        private static SteamVR_Action_Boolean p_hVR_RightSecondaryTouch;
        
        private static SteamVR_Action_Boolean p_hVR_RightMenu;
        
        private static SteamVR_Action_Boolean p_hVR_RightPrimaryAxisClick;
        
        private static SteamVR_Action_Boolean p_hVR_RightSecondaryAxisClick;
        
        private static SteamVR_Action_Boolean p_hVR_RightPrimaryAxisTouch;
        
        private static SteamVR_Action_Boolean p_hVR_RightTriggerTouch;
        
        private static SteamVR_Action_Boolean p_hVR_RightThumbTouch;
        
        private static SteamVR_Action_Boolean p_hVR_RightTriggerNearTouch;
        
        private static SteamVR_Action_Boolean p_hVR_RightThumbNearTouch;
        
        private static SteamVR_Action_Vector2 p_hVR_RightPrimaryAxis;
        
        private static SteamVR_Action_Vector2 p_hVR_RightSecondaryAxis;
        
        private static SteamVR_Action_Boolean p_hVR_RightSecondaryAxisTouch;
        
        private static SteamVR_Action_Boolean p_hVR_RightGripButton;
        
        private static SteamVR_Action_Boolean p_hVR_RightTriggerButton;
        
        private static SteamVR_Action_Skeleton p_hVR_left_skeleton;
        
        private static SteamVR_Action_Skeleton p_hVR_right_skeleton;
        
        private static SteamVR_Action_Vibration p_hVR_Haptics;
        
        private static SteamVR_Action_Vibration p_hVR_RightHaptics;
        
        public static SteamVR_Action_Boolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Teleport
        {
            get
            {
                return SteamVR_Actions.p_default_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single default_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_default_SnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 platformer_Move
        {
            get
            {
                return SteamVR_Actions.p_platformer_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean platformer_Jump
        {
            get
            {
                return SteamVR_Actions.p_platformer_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 buggy_Steering
        {
            get
            {
                return SteamVR_Actions.p_buggy_Steering.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single buggy_Throttle
        {
            get
            {
                return SteamVR_Actions.p_buggy_Throttle.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Brake
        {
            get
            {
                return SteamVR_Actions.p_buggy_Brake.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Reset
        {
            get
            {
                return SteamVR_Actions.p_buggy_Reset.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose mixedreality_ExternalCamera
        {
            get
            {
                return SteamVR_Actions.p_mixedreality_ExternalCamera.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Single hVR_LeftGrip
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftGrip.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single hVR_LeftTrigger
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftTrigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftPrimary
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftPrimary.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftPrimaryTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftPrimaryTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftSecondary
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftSecondary.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftSecondaryTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftSecondaryTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftMenu
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftMenu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftPrimaryAxisClick
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftPrimaryAxisClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftSecondaryAxisClick
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftSecondaryAxisClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftPrimaryAxisTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftPrimaryAxisTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftTriggerTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftTriggerTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftThumbTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftThumbTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftTriggerNearTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftTriggerNearTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftThumbNearTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftThumbNearTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 hVR_LeftPrimaryAxis
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftPrimaryAxis.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 hVR_LeftSecondaryAxis
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftSecondaryAxis.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftSecondaryAxisTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftSecondaryAxisTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftGripButton
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftGripButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_LeftTriggerButton
        {
            get
            {
                return SteamVR_Actions.p_hVR_LeftTriggerButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single hVR_RightGrip
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightGrip.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single hVR_RightTrigger
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightTrigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightPrimary
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightPrimary.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightPrimaryTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightPrimaryTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightSecondary
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightSecondary.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightSecondaryTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightSecondaryTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightMenu
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightMenu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightPrimaryAxisClick
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightPrimaryAxisClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightSecondaryAxisClick
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightSecondaryAxisClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightPrimaryAxisTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightPrimaryAxisTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightTriggerTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightTriggerTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightThumbTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightThumbTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightTriggerNearTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightTriggerNearTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightThumbNearTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightThumbNearTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 hVR_RightPrimaryAxis
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightPrimaryAxis.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 hVR_RightSecondaryAxis
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightSecondaryAxis.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightSecondaryAxisTouch
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightSecondaryAxisTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightGripButton
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightGripButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean hVR_RightTriggerButton
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightTriggerButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Skeleton hVR_left_skeleton
        {
            get
            {
                return SteamVR_Actions.p_hVR_left_skeleton.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton hVR_right_skeleton
        {
            get
            {
                return SteamVR_Actions.p_hVR_right_skeleton.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vibration hVR_Haptics
        {
            get
            {
                return SteamVR_Actions.p_hVR_Haptics.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vibration hVR_RightHaptics
        {
            get
            {
                return SteamVR_Actions.p_hVR_RightHaptics.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.hVR_LeftGrip,
                    SteamVR_Actions.hVR_LeftTrigger,
                    SteamVR_Actions.hVR_LeftPrimary,
                    SteamVR_Actions.hVR_LeftPrimaryTouch,
                    SteamVR_Actions.hVR_LeftSecondary,
                    SteamVR_Actions.hVR_LeftSecondaryTouch,
                    SteamVR_Actions.hVR_LeftMenu,
                    SteamVR_Actions.hVR_LeftPrimaryAxisClick,
                    SteamVR_Actions.hVR_LeftSecondaryAxisClick,
                    SteamVR_Actions.hVR_LeftPrimaryAxisTouch,
                    SteamVR_Actions.hVR_LeftTriggerTouch,
                    SteamVR_Actions.hVR_LeftThumbTouch,
                    SteamVR_Actions.hVR_LeftTriggerNearTouch,
                    SteamVR_Actions.hVR_LeftThumbNearTouch,
                    SteamVR_Actions.hVR_LeftPrimaryAxis,
                    SteamVR_Actions.hVR_LeftSecondaryAxis,
                    SteamVR_Actions.hVR_LeftSecondaryAxisTouch,
                    SteamVR_Actions.hVR_LeftGripButton,
                    SteamVR_Actions.hVR_LeftTriggerButton,
                    SteamVR_Actions.hVR_RightGrip,
                    SteamVR_Actions.hVR_RightTrigger,
                    SteamVR_Actions.hVR_RightPrimary,
                    SteamVR_Actions.hVR_RightPrimaryTouch,
                    SteamVR_Actions.hVR_RightSecondary,
                    SteamVR_Actions.hVR_RightSecondaryTouch,
                    SteamVR_Actions.hVR_RightMenu,
                    SteamVR_Actions.hVR_RightPrimaryAxisClick,
                    SteamVR_Actions.hVR_RightSecondaryAxisClick,
                    SteamVR_Actions.hVR_RightPrimaryAxisTouch,
                    SteamVR_Actions.hVR_RightTriggerTouch,
                    SteamVR_Actions.hVR_RightThumbTouch,
                    SteamVR_Actions.hVR_RightTriggerNearTouch,
                    SteamVR_Actions.hVR_RightThumbNearTouch,
                    SteamVR_Actions.hVR_RightPrimaryAxis,
                    SteamVR_Actions.hVR_RightSecondaryAxis,
                    SteamVR_Actions.hVR_RightSecondaryAxisTouch,
                    SteamVR_Actions.hVR_RightGripButton,
                    SteamVR_Actions.hVR_RightTriggerButton,
                    SteamVR_Actions.hVR_left_skeleton,
                    SteamVR_Actions.hVR_right_skeleton,
                    SteamVR_Actions.hVR_Haptics,
                    SteamVR_Actions.hVR_RightHaptics};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.hVR_LeftGrip,
                    SteamVR_Actions.hVR_LeftTrigger,
                    SteamVR_Actions.hVR_LeftPrimary,
                    SteamVR_Actions.hVR_LeftPrimaryTouch,
                    SteamVR_Actions.hVR_LeftSecondary,
                    SteamVR_Actions.hVR_LeftSecondaryTouch,
                    SteamVR_Actions.hVR_LeftMenu,
                    SteamVR_Actions.hVR_LeftPrimaryAxisClick,
                    SteamVR_Actions.hVR_LeftSecondaryAxisClick,
                    SteamVR_Actions.hVR_LeftPrimaryAxisTouch,
                    SteamVR_Actions.hVR_LeftTriggerTouch,
                    SteamVR_Actions.hVR_LeftThumbTouch,
                    SteamVR_Actions.hVR_LeftTriggerNearTouch,
                    SteamVR_Actions.hVR_LeftThumbNearTouch,
                    SteamVR_Actions.hVR_LeftPrimaryAxis,
                    SteamVR_Actions.hVR_LeftSecondaryAxis,
                    SteamVR_Actions.hVR_LeftSecondaryAxisTouch,
                    SteamVR_Actions.hVR_LeftGripButton,
                    SteamVR_Actions.hVR_LeftTriggerButton,
                    SteamVR_Actions.hVR_RightGrip,
                    SteamVR_Actions.hVR_RightTrigger,
                    SteamVR_Actions.hVR_RightPrimary,
                    SteamVR_Actions.hVR_RightPrimaryTouch,
                    SteamVR_Actions.hVR_RightSecondary,
                    SteamVR_Actions.hVR_RightSecondaryTouch,
                    SteamVR_Actions.hVR_RightMenu,
                    SteamVR_Actions.hVR_RightPrimaryAxisClick,
                    SteamVR_Actions.hVR_RightSecondaryAxisClick,
                    SteamVR_Actions.hVR_RightPrimaryAxisTouch,
                    SteamVR_Actions.hVR_RightTriggerTouch,
                    SteamVR_Actions.hVR_RightThumbTouch,
                    SteamVR_Actions.hVR_RightTriggerNearTouch,
                    SteamVR_Actions.hVR_RightThumbNearTouch,
                    SteamVR_Actions.hVR_RightPrimaryAxis,
                    SteamVR_Actions.hVR_RightSecondaryAxis,
                    SteamVR_Actions.hVR_RightSecondaryAxisTouch,
                    SteamVR_Actions.hVR_RightGripButton,
                    SteamVR_Actions.hVR_RightTriggerButton,
                    SteamVR_Actions.hVR_left_skeleton,
                    SteamVR_Actions.hVR_right_skeleton};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.hVR_Haptics,
                    SteamVR_Actions.hVR_RightHaptics};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.hVR_Haptics,
                    SteamVR_Actions.hVR_RightHaptics};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.hVR_LeftPrimary,
                    SteamVR_Actions.hVR_LeftPrimaryTouch,
                    SteamVR_Actions.hVR_LeftSecondary,
                    SteamVR_Actions.hVR_LeftSecondaryTouch,
                    SteamVR_Actions.hVR_LeftMenu,
                    SteamVR_Actions.hVR_LeftPrimaryAxisClick,
                    SteamVR_Actions.hVR_LeftSecondaryAxisClick,
                    SteamVR_Actions.hVR_LeftPrimaryAxisTouch,
                    SteamVR_Actions.hVR_LeftTriggerTouch,
                    SteamVR_Actions.hVR_LeftThumbTouch,
                    SteamVR_Actions.hVR_LeftTriggerNearTouch,
                    SteamVR_Actions.hVR_LeftThumbNearTouch,
                    SteamVR_Actions.hVR_LeftSecondaryAxisTouch,
                    SteamVR_Actions.hVR_LeftGripButton,
                    SteamVR_Actions.hVR_LeftTriggerButton,
                    SteamVR_Actions.hVR_RightPrimary,
                    SteamVR_Actions.hVR_RightPrimaryTouch,
                    SteamVR_Actions.hVR_RightSecondary,
                    SteamVR_Actions.hVR_RightSecondaryTouch,
                    SteamVR_Actions.hVR_RightMenu,
                    SteamVR_Actions.hVR_RightPrimaryAxisClick,
                    SteamVR_Actions.hVR_RightSecondaryAxisClick,
                    SteamVR_Actions.hVR_RightPrimaryAxisTouch,
                    SteamVR_Actions.hVR_RightTriggerTouch,
                    SteamVR_Actions.hVR_RightThumbTouch,
                    SteamVR_Actions.hVR_RightTriggerNearTouch,
                    SteamVR_Actions.hVR_RightThumbNearTouch,
                    SteamVR_Actions.hVR_RightSecondaryAxisTouch,
                    SteamVR_Actions.hVR_RightGripButton,
                    SteamVR_Actions.hVR_RightTriggerButton};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.hVR_LeftGrip,
                    SteamVR_Actions.hVR_LeftTrigger,
                    SteamVR_Actions.hVR_RightGrip,
                    SteamVR_Actions.hVR_RightTrigger};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.hVR_LeftPrimaryAxis,
                    SteamVR_Actions.hVR_LeftSecondaryAxis,
                    SteamVR_Actions.hVR_RightPrimaryAxis,
                    SteamVR_Actions.hVR_RightSecondaryAxis};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.hVR_left_skeleton,
                    SteamVR_Actions.hVR_right_skeleton};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_SnapTurnLeft,
                    SteamVR_Actions.default_SnapTurnRight,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.hVR_LeftGrip,
                    SteamVR_Actions.hVR_LeftTrigger,
                    SteamVR_Actions.hVR_LeftPrimary,
                    SteamVR_Actions.hVR_LeftPrimaryTouch,
                    SteamVR_Actions.hVR_LeftSecondary,
                    SteamVR_Actions.hVR_LeftSecondaryTouch,
                    SteamVR_Actions.hVR_LeftMenu,
                    SteamVR_Actions.hVR_LeftPrimaryAxisClick,
                    SteamVR_Actions.hVR_LeftSecondaryAxisClick,
                    SteamVR_Actions.hVR_LeftPrimaryAxisTouch,
                    SteamVR_Actions.hVR_LeftTriggerTouch,
                    SteamVR_Actions.hVR_LeftThumbTouch,
                    SteamVR_Actions.hVR_LeftTriggerNearTouch,
                    SteamVR_Actions.hVR_LeftThumbNearTouch,
                    SteamVR_Actions.hVR_LeftPrimaryAxis,
                    SteamVR_Actions.hVR_LeftSecondaryAxis,
                    SteamVR_Actions.hVR_LeftSecondaryAxisTouch,
                    SteamVR_Actions.hVR_LeftGripButton,
                    SteamVR_Actions.hVR_LeftTriggerButton,
                    SteamVR_Actions.hVR_RightGrip,
                    SteamVR_Actions.hVR_RightTrigger,
                    SteamVR_Actions.hVR_RightPrimary,
                    SteamVR_Actions.hVR_RightPrimaryTouch,
                    SteamVR_Actions.hVR_RightSecondary,
                    SteamVR_Actions.hVR_RightSecondaryTouch,
                    SteamVR_Actions.hVR_RightMenu,
                    SteamVR_Actions.hVR_RightPrimaryAxisClick,
                    SteamVR_Actions.hVR_RightSecondaryAxisClick,
                    SteamVR_Actions.hVR_RightPrimaryAxisTouch,
                    SteamVR_Actions.hVR_RightTriggerTouch,
                    SteamVR_Actions.hVR_RightThumbTouch,
                    SteamVR_Actions.hVR_RightTriggerNearTouch,
                    SteamVR_Actions.hVR_RightThumbNearTouch,
                    SteamVR_Actions.hVR_RightPrimaryAxis,
                    SteamVR_Actions.hVR_RightSecondaryAxis,
                    SteamVR_Actions.hVR_RightSecondaryAxisTouch,
                    SteamVR_Actions.hVR_RightGripButton,
                    SteamVR_Actions.hVR_RightTriggerButton};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Teleport")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Squeeze")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnLeft")));
            SteamVR_Actions.p_default_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SnapTurnRight")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            SteamVR_Actions.p_platformer_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/platformer/in/Move")));
            SteamVR_Actions.p_platformer_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/platformer/in/Jump")));
            SteamVR_Actions.p_buggy_Steering = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/buggy/in/Steering")));
            SteamVR_Actions.p_buggy_Throttle = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/buggy/in/Throttle")));
            SteamVR_Actions.p_buggy_Brake = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Brake")));
            SteamVR_Actions.p_buggy_Reset = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Reset")));
            SteamVR_Actions.p_mixedreality_ExternalCamera = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/mixedreality/in/ExternalCamera")));
            SteamVR_Actions.p_hVR_LeftGrip = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/HVR/in/LeftGrip")));
            SteamVR_Actions.p_hVR_LeftTrigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/HVR/in/LeftTrigger")));
            SteamVR_Actions.p_hVR_LeftPrimary = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftPrimary")));
            SteamVR_Actions.p_hVR_LeftPrimaryTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftPrimaryTouch")));
            SteamVR_Actions.p_hVR_LeftSecondary = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftSecondary")));
            SteamVR_Actions.p_hVR_LeftSecondaryTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftSecondaryTouch")));
            SteamVR_Actions.p_hVR_LeftMenu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftMenu")));
            SteamVR_Actions.p_hVR_LeftPrimaryAxisClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftPrimaryAxisClick")));
            SteamVR_Actions.p_hVR_LeftSecondaryAxisClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftSecondaryAxisClick")));
            SteamVR_Actions.p_hVR_LeftPrimaryAxisTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftPrimaryAxisTouch")));
            SteamVR_Actions.p_hVR_LeftTriggerTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftTriggerTouch")));
            SteamVR_Actions.p_hVR_LeftThumbTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftThumbTouch")));
            SteamVR_Actions.p_hVR_LeftTriggerNearTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftTriggerNearTouch")));
            SteamVR_Actions.p_hVR_LeftThumbNearTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftThumbNearTouch")));
            SteamVR_Actions.p_hVR_LeftPrimaryAxis = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/HVR/in/LeftPrimaryAxis")));
            SteamVR_Actions.p_hVR_LeftSecondaryAxis = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/HVR/in/LeftSecondaryAxis")));
            SteamVR_Actions.p_hVR_LeftSecondaryAxisTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftSecondaryAxisTouch")));
            SteamVR_Actions.p_hVR_LeftGripButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftGripButton")));
            SteamVR_Actions.p_hVR_LeftTriggerButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/LeftTriggerButton")));
            SteamVR_Actions.p_hVR_RightGrip = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/HVR/in/RightGrip")));
            SteamVR_Actions.p_hVR_RightTrigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/HVR/in/RightTrigger")));
            SteamVR_Actions.p_hVR_RightPrimary = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightPrimary")));
            SteamVR_Actions.p_hVR_RightPrimaryTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightPrimaryTouch")));
            SteamVR_Actions.p_hVR_RightSecondary = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightSecondary")));
            SteamVR_Actions.p_hVR_RightSecondaryTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightSecondaryTouch")));
            SteamVR_Actions.p_hVR_RightMenu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightMenu")));
            SteamVR_Actions.p_hVR_RightPrimaryAxisClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightPrimaryAxisClick")));
            SteamVR_Actions.p_hVR_RightSecondaryAxisClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightSecondaryAxisClick")));
            SteamVR_Actions.p_hVR_RightPrimaryAxisTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightPrimaryAxisTouch")));
            SteamVR_Actions.p_hVR_RightTriggerTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightTriggerTouch")));
            SteamVR_Actions.p_hVR_RightThumbTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightThumbTouch")));
            SteamVR_Actions.p_hVR_RightTriggerNearTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightTriggerNearTouch")));
            SteamVR_Actions.p_hVR_RightThumbNearTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightThumbNearTouch")));
            SteamVR_Actions.p_hVR_RightPrimaryAxis = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/HVR/in/RightPrimaryAxis")));
            SteamVR_Actions.p_hVR_RightSecondaryAxis = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/HVR/in/RightSecondaryAxis")));
            SteamVR_Actions.p_hVR_RightSecondaryAxisTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightSecondaryAxisTouch")));
            SteamVR_Actions.p_hVR_RightGripButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightGripButton")));
            SteamVR_Actions.p_hVR_RightTriggerButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HVR/in/RightTriggerButton")));
            SteamVR_Actions.p_hVR_left_skeleton = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/HVR/in/left_skeleton")));
            SteamVR_Actions.p_hVR_right_skeleton = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/HVR/in/right_skeleton")));
            SteamVR_Actions.p_hVR_Haptics = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/HVR/out/Haptics")));
            SteamVR_Actions.p_hVR_RightHaptics = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/HVR/out/RightHaptics")));
        }
    }
}
